semi: false
singleQuote: true
trailingComma: none
printWidth: 80
tabWidth: 2
useTabs: false
arrowParens: always
bracketSpacing: true
endOfLine: lf
proseWrap: always
quoteProps: as-needed
jsxSingleQuote: false
htmlWhitespaceSensitivity: css
yamlBracketSpacing: true
yamlKeySort: false
